name: QQNews

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup sparse-checkout
        run: |
          mkdir my_repo
          cd my_repo
          git init
          git config core.sparseCheckout true
          echo 'qq.py' >> .git/info/sparse-checkout
          echo 'requirements.txt' >> .git/info/sparse-checkout
          echo '2023/12/' >> .git/info/sparse-checkout
          git remote add -f origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'
          
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Commit files
        run: |
          cd my_repo
          git config --local user.email "378600950@qq.com"
          git config --local user.name "qqhsx"
          git pull origin main
          pip3 install requests
          pip3 install bs4
          pip3 install html2text
          python qq.py
          git add .
          git commit --allow-empty -m "spider"
          git push origin main
